version: '3'
services:
  node:
    restart: always
    build: 
      context: ./apis/api-nodejs/build
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - toutatix_net # Spécifie le même réseau virtuel que les autres conteneurs

  php_apache: # Nom du micro service (service web)
    build: # Instruction pour build l'image
      context: ./apis/api-php/build
      dockerfile: Dockerfile
    container_name: '${APP_NAME}-server' # Nom du container
    restart: always # Politique de redémarrage lorsque le serveur redémarre 
    ports:
      - '${APP_PORT}:80' # Port de l'application
    working_dir: /var/www/html # working dir
    environment: # variables d'environnement visibles à l'intérieur du conteneur "server"
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
      TZ: 'Europe/Paris' # TimeZone
    volumes: # Volumes du conteneur (cf. partie 1)
      - ./apis/api-php/app:/var/www/html
      - ./apis/api-php/images:/data
      - ./apis/api-php/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./apis/api-php/web/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      - db_server # Pour forcer l'ordre de démarrage des conteneurs
    networks:
      - toutatix_net # Spécifie le même réseau virtuel que les autres conteneurs

  db_server: # Nom du micro service de la BDD
    image: mariadb:latest # Basé sur une image officielle mariadb (dockerhub)
    container_name: '${APP_NAME}-db' # Nom du container
    restart: always # Politique de redémarrage lorsque le serveur redémarre 
    ports:
      - '${DB_PORT}:3306' # Port mysql
    environment: # variables d'environnement visibles à l'intérieur du conteneur "db_server" (requis pour mariadb)
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASS}'
      MYSQL_DATABASE: '${MYSQL_DB}'
    volumes:
      - ./db/data/:/var/lib/mysql # Le volume qui contiendra toutes les données persistentes de la BDD
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf # fichier de conf mariadb
      - ./db/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql # script d'initialisation de la BDD (lancé au démarrage de mariadb)
    networks:
      - toutatix_net # Spécifie le même réseau virtuel que les autres conteneurs

  db_admin: # Nom du micro service PhpMyAdmin
    image: phpmyadmin/phpmyadmin:5 # Basé sur une image officielle phpmyadmin (dockerhub)
    container_name: '${APP_NAME}-db-admin' # Nom du container
    restart: always # Politique de redémarrage lorsque le serveur redémarre 
    ports:
      - '${APP_DB_ADMIN_PORT}:80' # Port d'accès à la page web d'admin de PhpMyAdmin
    environment:
      PMA_HOST: db_server # Hostname (nom du micro-service dans la stack) du conteneur de BDD
    depends_on:
      - db_server  # Pour forcer l'ordre de démarrage des conteneurs
    networks:
      - toutatix_net # Spécifie le même réseau virtuel que les autres conteneurs


networks:
  toutatix_net:
